### PR TITLE
Ghost site

### PR DESCRIPTION
**Pull request by hamhands**
### What changed
- Killed signup form
- Removed RFP faq, referenced Beacon
### Screencap

screen shot 2015-09-15 at 12 18 17 pm

### CODE REVIEW

**Comment by msknee** [comment]
Yeah, will make copy changes today!

**Comment by hamhands** [comment]
@shellicious I'd like to merge this today. If you're having problems setting up Jekyll, you can just send me the copy.

**Comment by msknee** [comment]
Copy change: 

White text: The Citiparks cleaning services opportunity closed on May 8th, 2015. 

Yellow text: Find other City of Pittsburgh opportunities on (link) Beacon.

Below the fold:

This page provided information about a Citiparks cleaning services opportunity. The bidding window lasted from Month, Day, 2015 to May 8th, 2015. Although bidding is over, you can still read the RFP (link).

**Comment by hamhands** [comment]
How's this @shellicious?
screen shot 2015-09-20 at 7 28 37 pm

**Comment by msknee** [comment]
Make the Beacon link yellow, get rid of the "what is this?" header and comments link, and we're good to go!

**Comment by hamhands** [comment]
@shellicious :ok: :white_check_mark:

**Pull request merged**
