### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by hamhands**
### What changed
- Major style changes
- Initial copy to FAQify RFP content
- Added a footer.html template
### What needs to be done
- Final copy edits/additions
- Font size tweaking for mobile
### Screencap

new

### CODE REVIEW

**Comment by bsmithgall** [comment]
Are you adding the disqus inline for this? You should be able to steal it right out of #14

**Comment by bsmithgall** [comment]
Also, take the changes to the config.yml from #14 for sure.

**Comment by hamhands** [comment]
@bsmithgall is that something we want for production day one? I can add it in, but I'd rather finish the content first and then add the inline stuff tomorrow.

**Comment by bsmithgall** [comment]
Sounds good :sparkles:

**Comment by hamhands** [comment]
That might be a heavier lift though. Looking at #14 I've got a lot to fix in index.html

**Comment by bsmithgall** [comment]
This is a dupe of #17

**Pull request closed without merging**
