### PR TITLE
added basic parks rfp, inline comments [WIP]

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added the language from the parks RFP (converted from .docx -> markdown, this was terrible to do)
- Added [inlineDisqussions](http://tsi.github.io/inlineDisqussions/)
### Issues

None
### Screencap

template-maker-current-flow
### Still TODO
- Clean up CSS
- Maybe add more of the RFP (the information about facilities?)
- Discuss this as a possibility around facilitating vendor Q&A?

### CODE REVIEW

**Comment by hamhands** [comment]
Nice. This looks really good. 

:+1: LGTM x one million

**Comment by bsmithgall** [comment]
It's still kind of messy; you should pull down the branch and see if you can clean it up a bit. Also, I'm not sure if the RFP language is the most recent.

.docx --> markdown process:
- Upload .docx to Google Docs
- Run [this plugin](http://lifehacker.com/this-script-converts-google-documents-to-markdown-for-e-511746113)
- Profit

Obviously this is not scalable, but I can't figure out a better way to do this (the html generated by the word docs is also unbelievably bad).

**Comment by hamhands** [comment]
I'm putting the contact info into the map, but we could add pages for each facility maybe?

**Comment by bsmithgall** [comment]
I think that you should include the things that need to be done at each facility (like in popups or something).

**Comment by hamhands** [comment]
Maybe...that might be way too much info for a popup though

**Comment by bsmithgall** [comment]
I don't know the best place to put it, but it would be way more digestible than the current mega-word form, and would probably be nice to have filters or whatever (only show me points with gyms, for example)

**Comment by hamhands** [comment]
My preference would be a "More details..." link in a popup that leads to a page for that facility.

**Comment by hamhands** [comment]
Once we get the map up we can talk about adding that stuff

**Comment by msknee** [comment]
@bsmithgall functionality is cool! 

-- what does the flow look like if you haven't signed up for Disqus?
-- There should be a prompt at the top of the page, like: "Questions about this RFP? Leave a comment on any section, and we'll get back to you by April XX."

**Comment by hamhands** [comment]
Tacking on to @shellicious comment on questions: we're planning on forwarding these to Louann, right? I'm a bit concerned that the RFP says one thing while our interface is saying another.

**Comment by bsmithgall** [comment]
You have to sign in with Disqus, but I think there's a way to leave a comment as a guest. I'm not super familiar with Disqus but you can poke around. Login is same as the tumblr: https://disqus.com/profile/login/?next=https%3A%2F%2Fdisqus.com%2F

**Comment by bsmithgall** [comment]
Closing in favor of #19

**Pull request closed without merging**
